name: cuidapet_api
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.1.3
  dotenv: ^3.0.0-nullsafety.0
  mysql1: ^0.20.0
  get_it: ^7.2.0
  logger: ^1.1.0
  injectable: ^1.5.3
  jaguar_jwt: ^3.0.0


dev_dependencies:
  pedantic: ^1.10.0
  injectable_generator: ^1.5.4
  build_runner: ^2.2.0
  shelf_router_generator: ^1.0.3

dependency_overrides:
  analyzer:
